#!/bin/sh
#------------------------
# Testing starter, charon
#------------------------
DAEMONS="starter charon"

# make sure charon is started
invoke-rc.d strongswan-starter start
sleep 1
invoke-rc.d strongswan-starter status

for daemon in $DAEMONS; do
    if pidof -x $daemon > /dev/null; then
        echo "$daemon OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
